on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - name: create env file
        run: |
          touch .env
          echo MONGO_DB="mongodb+srv://" + ${{ secrets.MONGO_USER }} + :${{ secrets.MONGO_PWD }} + "@cluster0.czex64t.mongodb.net/actionsdb?retryWrites=true&w=majority" >> .env
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test
      - run: node server.js
